# Generated by Django 4.2 on 2024-11-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_name_alter_amenity_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='country',
            field=models.CharField(default='한국', max_length=50),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(default='', max_length=180),
        ),
    ]
